### ISSUE TITLE
How install MongoDB plugin?

### ISSUE THREAD

**Issue by TimBobkov** [cocaine/cocaine-plugins#110]
Hello.
How can I install mongodb-plugin? I try install from git but get some errors during compilation...

**Comment by 3Hren** [comment]
You should use the [fuck](https://github.com/nvbn/thefuck) utility.

Otherwise we'll glad to see the `make` console output to be able to find out what's going on.

**Comment by 3Hren** [comment]
Okay, feel free to reopen this issue if you still having troubles with installing.
