### ISSUE TITLE
cocaine plugin urlfetch doesn't compile

### ISSUE THREAD

**Issue by kazan417** [cocaine/cocaine-plugins#79]
i am trying to compile cocaine-plugins, but getting error

[ 26%] Building CXX object urlfetch/CMakeFiles/urlfetch.dir/src/urlfetch.cpp.o
/home/mikhail/cocaine-yandex/plugins/cocaine-plugins/urlfetch/src/urlfetch.cpp:                                              In member function ‘void {anonymous}::urlfetch_get_handler::operator()(const ior                                             emap::swarm::url_fetcher::response&, const string&, const boost::system::error_c                                             ode&)’:
/home/mikhail/cocaine-yandex/plugins/cocaine-plugins/urlfetch/src/urlfetch.cpp:1                                             36:63: error: no matching function for call to ‘cocaine::deferred<std::tuple<boo                                             l, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int,                                              std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >,                                              std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::le                                             ss<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std                                             ::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std:                                             :allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocat                                             or<char> > > > > > >::abort(int, std::string)’
                                               error.message()));
                                                               ^
/home/mikhail/cocaine-yandex/plugins/cocaine-plugins/urlfetch/src/urlfetch.cpp:1                                             36:63: note: candidate is:
In file included from /usr/include/cocaine/rpc/dispatch.hpp:28:0,
                 from /home/mikhail/cocaine-yandex/plugins/cocaine-plugins/urlfe                                             tch/include/cocaine/urlfetch.hpp:21,
                 from /home/mikhail/cocaine-yandex/plugins/cocaine-plugins/urlfe                                             tch/src/urlfetch.cpp:18:
/usr/include/cocaine/rpc/slot/deferred.hpp:122:5: note: cocaine::deferred<T>& co                                             caine::deferred<T>::abort(const std::error_code&, const string&) [with T = std::                                             tuple<bool, std::basic_string<char, std::char_traits<char>, std::allocator<char>                                              >, int, std::map<std::basic_string<char, std::char_traits<char>, std::allocator                                             <char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >                                             , std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char>                                              > >, std::allocator<std::pair<const std::basic_string<char, std::char_traits<ch                                             ar>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std                                             ::allocator<char> > > > > >; std::string = std::basic_string<char>]
     abort(const std::error_code& ec, const std::string& reason) {
     ^
/usr/include/cocaine/rpc/slot/deferred.hpp:122:5: note:   no known conversion fo                                             r argument 1 from ‘int’ to ‘const std::error_code&’
make[2]: *** [urlfetch/CMakeFiles/urlfetch.dir/src/urlfetch.cpp.o] Ошибка 1
make[1]: *** [urlfetch/CMakeFiles/urlfetch.dir/all] Ошибка 2
make: *** [all] Ошибка 2

gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

**Comment by 3Hren** [comment]
That's why the appropriate method is statically suppressed here: https://github.com/cocaine/cocaine-core/blob/v0.12/include/cocaine/rpc/slot/deferred.hpp#L127

@kobolog why?

**Comment by 3Hren** [comment]
Upd: oops, you're probably using v0.12 branch, which is currently in WTF state, use v0.12-bleeding-edge for error category support or wait until we merge it.

**Comment by kazan417** [comment]
Thank you, just now succesfull compile v0.12-bleeding-edge. But wy it is not default branch?

**Comment by 3Hren** [comment]
We're currently in the middle of a huge merging process, our fault.
